### ISSUE TITLE
CORE/PROCESSOR: Duplicate scenario name suggested

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#106]
From @jsfried.
The following steps will recreate the problem in both CORE and PROCESSOR:
1. Delete a scenario (scenario3)
2. Create a new scenario (scenario4). Close
3. Create a new scenario again. Scenario4 is the name suggested which is a duplicate

**Comment by lbross** [comment]
The algorithm for suggesting a scenario name relied on the scenario count. For example, if there were 5 scenarios, it suggested scenario6. Given that scenarios don't always follow this naming convention, the algorithm was too simplistic. Updated it to query all the scenario names into a collection. Then check this collection for the existence of scenario1, scenario2, etc. Suggest the lowest one that doesn't already exist. This will be in the next BioSum release.

Also verified that BioSum checks for duplicate scenario names before saving.

**Comment by jsfried** [comment]
Thanks, that seems like good logic.

**Comment by jsfried** [comment]
Works well.

**Comment by jsfried** [comment]
My bad. This does not quite work in either processor or core. When I validated yesterday, I thought that there must have been a space between o and 1 and that was why I was getting a suggested name of scenario1, but I have now checked more carefully and am certain this is not the case. I have an existing scenario1. I create a new scenario and it suggests scenario1 as the name to use. If I click OK, at least it has the sense to tell me it is a no-go because it would duplicate an existing name. But it would be even more swell to suggest scenario2.

**Comment by jsfried** [comment]
The scenario creation and deletion action now works flawlessly, based on my testing, in both processor and core. Users should be urged (in documentation and help screen) to choose more evocative names than scenario1, scenario2, etc. for their own sanity however.
