### ISSUE TITLE
CORE: Implement weighted average capability

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#109]
Using example algorithm provided by @sloreno. We will calculate the weighted average for and FVS variable for a grow-only prescription for 4 cycles and put it in the PRE variable. Then calculate the weighted average for the other prescriptions and place in the POST variable. Then we use the existing interface to compare PRE/POST values to determine effectiveness.

**Comment by lbross** [comment]
Also included in this issue is renaming Core Analysis to Treatment Optimizer

**Comment by jsfried** [comment]
Nice job. I am happy to report that the calculate variables function seems to be working well and I have verified for one stand that all the calculated numbers are correct (I used a combination of three FVS variables, two that were calculated and one that was conventional pre vs post, plus a calculated economic variable for tie breaking). 

There are a couple of minor tweaks that would improve the Calculated Variables interface:
1)	When you look at the properties of an already calculated variable, the table and variable name appear in a blue highlighted background that makes the text invisible—could that be changed?
2)	Apparently, it assumes that the silvicultural sequence with the highest number is the base case, by default. But in CEC, it is not (31 is the grow-only; 32 and 33 are clearcuts). For each new calculated variable I make I have to remember to go change the 33 to 31. It would be better for it to be left blank when the dialog opens; then you could be prevented from saving the specs until you DO choose a base sequence.
3)	A minor blemish: In the main Define Calculated Variables dialog (that lists all the standard ones plus those you’ve created) the highlighting of the selected row is kind of “messy” in that:
a.	The highlight on the Variable Name column is different than for the other columns (ocean blue instead of royal blue, on my computer)
b.	The highlight on the Variable Name column does not fill the entire row in that column the way it does in the other columns
c.	Because of (b), clicking on a green (alternate) row changes the green to white in part of column 1 (that doesn’t receive the mis-colored highlighting)

**Comment by lbross** [comment]
Responding to @jsfried requests for UI enhancement:
1. This is the default style for disabled ListBoxes in Windows Forms. As a workaround I enabled the ListBoxes but capture the focus() event and immediately set the focus to a read-only label so that the ListBoxes are effectively disabled if the form is in read-only mode.
2. Made requested change
3. Setting the fullRowSelect property of the ListView to true solves this problem. This is the same setting we use for the ListView on the upper half of uc_processor_tree_spc.cs

Items 1 and 2 were implemented on 11-JAN. Item 3 will be implemented with the next BioSum release

**Comment by lbross** [comment]
Update grid on display for FVS weighted variable input to not show the sequence number but to show a pre/post indicator. This will streamline processing because we don't need to query the sequence number tables. We will still display the rxyear but this information will come from the FVS pre/post tables. Also the grid will need to be reloaded each time an FVS variable is selected, either new or display, because the FVS source tables may have unique rxyears. For example POTFIRE. See [updated design document](https://usfs.box.com/s/dvp1k0elx6l3hinpl78i29nlor3cj1vo).

**Comment by lbross** [comment]
Hoping that @sloreno  can validate this when she gets to Treatment Optimizer for BlueDemo.

**Comment by lbross** [comment]
Closing per @sloreno !
