### ISSUE TITLE
PROCESSOR: Updates to tree_species table

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#121]
1. Set id as primary key to match Tables.CreateTreeSpeciesTableIndexes(). This is also best practice for MS Access primary keys
2. Add composite unique values constraint for fvs_variant and spcd to prevent duplicates
3. Verify that fvs_input_spcd is a required field
4. Update fvs_input_spcd for 6 fvs_variant/spcd combinations where current fvs_input_spcd doesn't exist in fvs_tree_species table. See attached.

Updated attachment:
[Bad_FVS_INPUT_SPCD.xlsx](https://github.com/USFS-PNW/Fia-Biosum-Manager/files/1647743/Bad_FVS_INPUT_SPCD.xlsx)

**Comment by jsfried** [comment]
This does seem to have solved the issues, at least as tested with the Blue Mountains 10 demo project. 
However, there are 371 white fir (species code 15) trees in that project and both Tree_species and FVS_TREE_SPECIES map these to 17 (Grand fir). Great. But when I attempt to run processor on package 1, which contains no species code 15 trees in the BioSumCalc database containing the cutlist for package 1, I get this error message:
![image](https://user-images.githubusercontent.com/17485472/35789923-60c6cc92-09f4-11e8-94be-6fd8e450aefa.png)

It turns out that even though these white firs do not show as white firs in the cut list, BioSum knows that they are white firs (because they started as white firs), so wants white fir to be assigned to a species group. Adding white firs to the hem/fir species group solved the issue and allowed BioSum to proceed.

**Comment by lbross** [comment]
I believe this is working as designed. If trees aren't created by FVS, we map them back to their original spcd in master.tree. I double-checked to verify that 'white fir' shows on the Tree Species Groups screen with an '*' to indicate that it was used in the project. And it does.
