### ISSUE TITLE
PROCESSOR: Changes to application of some OPCOST minimum adjustments

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#122]
There is a logic error that applies the OpCost minimum volume adjustments when the TPA for a plot is zero. This is difficult to identify in opcost_input because the unadjusted volume is 0. I will update the code to only apply the volume adjustments for plots where TPA is > 0 for both large and small logs. Conor has a band-aid in place in OpCost to handle this.

**Comment by jsfried** [comment]
I’ve been working with Conor on the min tpa issue and we have reached some conclusions and are near to others.

There is no reason to have a min tpa for large log trees. Conor has confirmed this empirically with the various harvest systems running plots through OpCost. I wondered why there would be a minimum for those because, operationally, they are almost always felled by a faller with a chainsaw, then hauled away the same as every other utilized tree in the stand (small log and chip size). There should be nothing special about fallers that would preclude them from being used on one tree per acre (or even a fractional tree per acre). Under FRCS (the pre-Op_Cost solution for estimating treatment costs), we had many mins and maxes on tree sizes (avg volume), slope, distance and other metrics but most of those limits are now internally trapped for and "band-aided" within OpCost. The min TPA limit was new to OpCost and was instituted because in some systems, very low TPA generated very weird cost estimates by virtue of how TPA enters into the equations, I suppose, hence the limits. But these were only intended to apply to the small tree processing and due to miscommunications, this is not how they were implemented in BioSum. So, we need to NOT adjust large tree TPA and use the limits in the harvest_methods table only to adjust small tree TPA (when not 0). Conor may have some lower minimums to advise us on for some harvest systems and when ready, we will implement these in a revision to the harvest_methods table content for these systems. However, there is no reason not to cancel the adjustment of large tree tpa immediately. 

If I understand OpCost correctly, it should return correct cost estimates for all of these cases:

non-zero BC TPA, zero small and large TPA (no adjustments)
any BC TPA, non-zero but below the minimum small TPA, any large TPA (small TPA will be adjusted up by BioSum to the minimum)
any BC TPA, zero TPA and any zero or non-zero large TPA (no adjustments needed)
any BC TPA, non-zero but above the minimum small TPA, any zero or non-zero large TPA (no adjustments needed)

I am leaving this issue open until the BioSum code has removed the adjustment for large tree TPA and the harvest_methods table has been updated with new values for the small tree TPA, as needed.

**Comment by jsfried** [comment]
I just realized that I conflated min vol and min tpa, sorry about that. The min TPA issue is perhaps separate, though related. Can the title of this issue thread be adjusted to include both?

**Comment by lbross** [comment]
@jsfried: Removing the adjustment for large tree TPA is a minor code change that we could implement in a bug release for 5.8.0. Updating the values for min_tpa on the harvest_methods table is a change to the database schema and would require updating the release number to 5.8.1 so that we can automatically update the table on existing projects when they are upgraded. 

My preference is to do a bug fix for the large log tpa issue in 5.8.0, close this issue, and open a new one for updating the harvest_methods table since we may not release 5.8.1 for a couple of months. The values in harvest_methods could be manually updated in the meantime.

Does this work for you?

**Comment by lbross** [comment]
Created new issue #127 to address changes to harvest_methods table. This issue can be closed when we have verified that we are no longer adjusting min TPA for large log trees in v5.8.0.

**Comment by carlinstarrs** [comment]
I checked OpCost_Input large log trees per acre values in 5.8.0 that had been set to integer limits in 5.7.9 (3 or 10) and they seem to be real numbers now.

**Comment by lbross** [comment]
Closing. @carlinstarrs I think you have permission to close the issue after validating. Feel free to do so.
