### ISSUE TITLE
PROCESSOR: Updates to harvest_methods table

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#127]
We will add a new 'tethered logging' harvest system to the harvest_methods table. We may also update the min_tpa values for some of the harvest systems depending on feedback from Conor. The schema for the table may change if we have different min_tpa values for small and large logs.

I also like to resolve part of issue #60 by removing columns required by FRCS (Max ...) since we will already be distributing a new harvest_methods table as part of version_control.

**Comment by lbross** [comment]
Removed references to columns required by FRCS (Max ...) in code. Still toDo is removing these columns from the harvest_methods table in ref_master.mdb that we distribute. Waiting until closer to implementation so we don't break anything in 5.8.0.

**Comment by lbross** [comment]
Updated code to move harvest_methods table to biosum_ref.accdb

**Comment by lbross** [comment]
Need to move harvest_methods table back to project-specific ref_master.mdb. Due to refactoring of OpCost this table is in flux and needs to be both editable and project-specific. We may also move this table into the same database as some new OpCost control tables. 

@jsfried: Which version of the harvest_methods table do you want me to include with the FVS test .msi? My suggestion is the same table we released with 5.8.0 which would not include tethered logging or the updated volume limits. I removed the FRCS-specific columns in this revision and assume I should leave that change in place?

**Comment by jsfried** [comment]
Fine to remove the FRCS deprecated columns.

I would like tethered logging included but the volume limits NOT updated. Tethered logging needs to come in twice, because it works under steep and gentle slopes. I have been assigning it system 9 for gentle slopes and system 54 for steep slopes, with the same limits on each:

HarvestMethodID | STEEP_YN | Method | Description | MaxTreeVolumeFt3Chips | MaxTreeVolumeFt3ChipsDefault | MaxTreeVolumeFt3ChipsCellLocation | MaxTreeVolumeFt3SmallLogs | MaxTreeVolumeFt3SmallLogsDefault | MaxTreeVolumeFt3SmallLogsCellLocation | MaxTreeVolumeFt3LargeLogs | MaxTreeVolumeFt3LargeLogsDefault | MaxTreeVolumeFt3LargeLogsCellLocation | MaxTreeVolumeFt3AllLogs | MaxTreeVolumeFt3AllLogsDefault | MaxTreeVolumeFt3AllLogsCellLocation | MaxTreeVolumeFt3AllTrees | MaxTreeVolumeFt3AllTreesDefault | MaxTreeVolumeFt3AllTreesCellLocation | MaxTreeVolumeFt3PercentLgLogsToAllLogs | MaxTreeVolumeFt3PercentLgLogsToAllLogsDefault | MaxTreeVolumeFt3PercentLgLogsToAllLogsCellLocation | MaxTreeVolumeFt3LgLogsPerAcre | MaxTreeVolumeFt3LgLogsPerAcreDefault | MaxTreeVolumeFt3LgLogsPerAcreCellLocation | MaxSlopePercent | MaxSlopePercentDefault | MaxSlopePercentCellLocation | MaxYardingDistance | MaxYardingDistanceDefault | MaxYardingDistanceCellLocation | biosum_category | min_yard_distance_ft | min_tpa | min_avg_tree_vol_cf
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
9 | N | Tethered Harvester | Tethered |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 3 | 150 | 20 | 8

**Comment by lbross** [comment]
Update Method column from 'Tethered Harvester' to 'Tethered CTL'. @carlinstarrs needs to do the same in OpCost 10.0 to keep things in sync.

**Comment by lbross** [comment]
Closing. New harvest_methods table was implemented with v5.8.1. We've been using tethered CTL successfully for a while.
