### ISSUE TITLE
CORE: Changes to Treatment Intensity aka Last TieBreak Rank

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia-Biosum-Manager#129]
In core analysis, users have the option of specifying an FVS variable to serve as a tie breaker or to choose, and set or adjust levels of, Treatment Intensity. Depending on the optimization variable selected, there can frequently be ties needing resolution, so consistent handling of this chore is important. If an FVS variable is selected and edited, the user has a choice to assign best, in the case of ties, to treatments that max or min the specified FVS post or change variable. For Treatment intensity, there is no max or min option and it is not stated anywhere whether max or min are applied when breaking ties via intensity values. If it is Min, then it should say "Min" in the Max/Min column of the grid rather than NA. And Value Source could name the table where the treatment intensity codes live. Moreover, it is my understanding that intensity based tie-breaking is active irregardless of whether or not an FVS variable has been selected for tie-breaking, presumably as a secondary tie break. What happens when both rows in this table are checked:
![image](https://user-images.githubusercontent.com/17485472/36390146-cba349ce-1556-11e8-86f2-516770c16085.png)

It what happens any different than when only the FVS variable is checked? 

An indication (text) is needed on the treatment intensity specification screen that when intensity is used to break ties, the tie always goes to the treatment with the lowest intensity value, and if intensity is in fact always used, even if secondarily to the FVS variable, it's box should remain checked, since it is not really optional to the user (i.e., not be uncheckable).

**Comment by lbross** [comment]
The min value is used when breaking ties using Treatment Intensity. Agreed that it would be helpful to populate the MAX/MIN field on the Tie Breaker settings screen with MIN for the treatment intensity method. Disagree with setting Value Source field to 'scenario_rx_intensity'. We want the user to use the BioSum interface to update the values rather than going directly to the table.

Recommend adding this verbiage above the table on the Treatment Intensity page: "When treatment intensity is used to break ties, the tie goes to the treatment with the lowest rx_intensity value"

Currently, if both rows on the 'define tie breakers' grid are checked, the FVS variable tiebreaker logic is applied first. If > 1 stand wins the tiebreaker, the stand with the lowest intensity value wins the tie.

Intensity-based tie-breaking is NOT active unless the box is checked. After reviewing an e-mail titled "Copying treatment intensity" from August 30, 2017, I believe that it SHOULD be as the propensity for unbroken ties without it is high, and this can inflate the the wood values and volumes if a stand is represented > once in the summing process. If we turn it on to be always active, its box SHOULD be permanently checked since it would not be optional.

Given the possibility that stands can be over-represented if treatment intensity is not used, I feel this should be implemented soon, prior to the Core analysis redesign. But, I won't make the changes to require treatment intensity until I receive confirmation that we want to do this.

**Comment by jsfried** [comment]
I thought I had understood from Lesley a while back that intensity WAS always used as the last tie-breaker for just this reason (inflation of wood yield, etc., if there are unbroken ties remaining). If this is not the case, it should definitely be fixed as a priority before core analysis development (sigh). Agree with all else in Lesley's analysis.

**Comment by lbross** [comment]
It was my recollection that intensity was always used but after closely reviewing the e-mail from August 30, 2017, it appears that we came to agreement that it should always be used but this was never implemented in the system. My code review supports that it has not yet been implemented. This will be at the top of my list.

**Comment by lpotts** [comment]
Treatment intensity is the final resolver for breaking ties.  -Larry

**Comment by sloreno** [comment]
Can we have it so users can pick if they want intensity to be the backup tiebreaker? In almost every case in which I have had to assign intensity values to treatments, it didn’t make any sense. When looking at 30+ treatments, many of which are similar in intensity, it is impossible to apply a single value to packages (as repeating values are not allowed) that has any shred of meaning. I would much rather assign another FVS variable as a backup tiebreak. Being forced to assign arbitrary intensity values before continuing in core analysis, will always darken my mood.

**Comment by jsfried** [comment]
I think the problem is that biosum can’t anticipate how many ties there might be. If you have 30 treatments, it is conceivable that 30 tie breakers could be required to come up with a unique solution for each stand. Are you prepared to specify 30different tie breakers if you have 30 packages? Would you be happier with a random tie break value be applied to the last tie break so that the final tie break will be different with each run for a given stand? That introduces non repeatability into biosum which could also be problematic. As a secondary tie break, it is not necessary that it make sense, but I can understand a concern about systematic bias towards treatments arbitrarily labeled low intensity.

Sent from my iPad

On Feb 20, 2018, at 4:27 PM, sloreno <notifications@github.com<mailto:notifications@github.com>> wrote:

Can we have it so users can pick if they want intensity to be the backup tiebreaker? In almost every case in which I have had to assign intensity values to treatments, it didn’t make any sense. When looking at 30+ treatments, many of which are similar in intensity, it is impossible to apply a single value to packages (as repeating values are not allowed) that has any shred of meaning. I would much rather assign another FVS variable as a backup tiebreak. Being forced to assign arbitrary intensity values before continuing in core analysis, will always darken my mood.

**Comment by sloreno** [comment]
I don’t see the likelihood of ties being that great, unless an integer hazard score type of variable is used rather than a double type variable such as surface flame height or torch. Would post BA be just as good an indicator as an assigned intensity score to represent treatment intensity?

**Comment by lbross** [comment]
Larry ... please review uc_core_scenario_run.Cycle1_best_rx_summary(). Starting on about line 7127 there is a 3-way if-then statement that processes 3 different ways depending on which combination of checkboxes is selected. It appears, to me, that treatment intensity is only used when its checkbox is selected. But yes ... if it is used in combination with FVS variable(s), it is the last resolver applied.

Maybe @sloreno's objection is why we didn't implement this earlier? Will hold off on any code changes to require treatment intensity until we reach a consensus.

**Comment by jsfried** [comment]
Popular thread :-) 

Since we are mainly using integer hazard score variables in our current effectiveness logic these days in multiple projects, I suspect there is a propensity to produce a considerable number of multi-way ties. Sara, if you want to use post_BA to break ties, can't you specify that as the tie breaker FVS variable? If BA is unique for each Rx that comes in as optimal, that will produce a definitive treatment selection; if not, intensity (or whatever numbers are entered in that field) will kick in as a secondary tie breaker. Since BA is not the last word with respect to intensity (it could be argued that post QMD and/or max dbh cut matter too), you could set your intensities such that a MaxDBH gets 1 or 2 while a MaxDBH of 36 gets a 30 or 31. Are you saying that 1 FVS tie breaker variable is inadequate? How many would you like? 2? 3? And we'll still need "intensity" to cover cases where ties are still not broken. I am happy to rename the variable to Last Tie-Break to remove all connotation of intensity. If we had 2 FVS tiebreaks, then whichever one(s) were checked would be sequential tie breakers (in table order-- you could also call them TieBreak 1, TieBreak 2 and Last TieBreak instead of FVS variable or intensity. Last TieBreak would always be checked and you could check up to two TieBreaks ahead of it. I guess this will make Lesley's work on line 7127 a bit harder, but it should still be doable.

btw, I just figured out why replying to github email notifications is a bad idea, as it clogs up the thread with extra copies of earlier parts of the thread (sorry if my lingo is all wrong). Fortunately I could edit out the redundancies in my own previous post when commenting properly on the github site.

**Comment by lpotts** [comment]
The treatment intensity was  optional at one time, but Jeremy wanted it to be required.  Obviously, it was never implemented to be a required tiebreaker.

**Comment by jsfried** [comment]
To clarify, like Sara, I have not been a fan of treatment intensity for the last few years (once we moved to projects with LOTS of treatments of complexity that defied this over simple concept of assigning an intensity). However, once we learned from Larry and Lesley that without a unique tie break, we would obtain corrupted results because wood volume and value outputs (perhaps costs too) would be double counted for stands with unresolved ties due to the way in which the SQL was constructed that calculates aggregate info that ends up in the psite and owner summary tables, it became clear that a LastTie containing unique values (i.e., a key field) was critical. Intensity is currently serving that purpose. And per Sara's request, thanks to Lesley's edits, it now auto-populates with Rx numbers (which are guaranteed unique), saving analysts the bother of entering values for intensity when they don't want to. However, if it is not being used in core analysis because an FVS variable was selected instead and/or it is left unchecked, then corrupt output is likely when there are ties that don't break on the FVS selected variable. 

I thought I would have been content with BioSum just picking the first case in the list, when there were ties not resolved by the user selected variable, but in retrospect, that was a faulty assumption because outcomes (which Rxs were assigned to which stands) could vary among Core Analysis runs on the same dataset if tables on which results depend happen to have been resorted by an analyst viewing them in Access, for example. Such stochastic model behavior would be unwelcome and time consuming to explain, so a firmer/tighter protocol was needed. Intensity (or Last TieBreak, if you prefer), gets us there.

**Comment by lbross** [comment]
I'll preface this by asking if @sloreno is available at any point during the DEV call tomorrow (1:30 - 2:30) to discuss this issue?

A couple of related thoughts I had overnight. As @jsfried pointed out, treatment intensity is now auto-populated for new projects and copied when scenarios are copied, easing the burden on the analyst. We could:
1. Select treatment intensity by default for new projects. Currently undefined FVS variable is the default. This would encourage novice users to use treatment intensity.
2. Pop a warning message box when treatment intensity is de-selected telling the user that they may be permitting corrupted results by unchecking it. (I know there is a better way to say this)
3. Add an additional explanation to the treatment intensity page explaining that it should be used as a final tiebreaker
4. Rename treatment intensity to 'Last TieBreak' or 'Tie-break Rank'. I had balked at this earlier due to the level of work but now that I'm more familiar with Core Analysis, I don't think it would be that hard. 

Any of these changes could be made individually or together. It would make it harder for an untrained analyst to make an accidental mistake but not require a sophisticated analyst like @sloreno to use functionality that they don't want.

Adding additional FVS tie-breaker variables is a significant undertaking and I don't know that the value-add would be comparable to the development and testing efforts required.

**Comment by lpotts** [comment]
Maybe one of the options would be during the core analysis run is to have BIOSUM detect ties, interrupt the core analysis run,  and display a dialog listing just the records that are tied, and allow the user the option to select which package/treatment to move forward with.

-Larry

**Comment by lbross** [comment]
I thought about that but we don't do much in-process auditing in BioSum. Maybe an post-run audit? Or a warning message when it completes?

**Comment by lpotts** [comment]
Doing a post-run audit is too late by then since the application has completed all the aggregated summing.

**Comment by jsfried** [comment]
I don't think we want to require any analyst intervention in core analysis. A pre-audit is not possible because if a decision variable used for effectiveness or optimization involved economic stuff like net rev, we can't know those values until after core analysis has completed (and linked in the haul costs etc). So preparing for all eventualities is the only feasible approach and a Last Tiebreaker does that. If the analyst wants to check whether that (potentially arbitrary) Last Tiebreaker got used, I think they can consult the existing tiebreak audit tables, or perhaps a slight reconfiguration of these might be warranted.

**Comment by lbross** [comment]
Per our meeting on 22 February, we will make the following changes:

1. Rename 'Treatment Intensity' to 'Last TieBreak Rank'
2. Require Last TieBreak Rank as a tiebreaker and always check the box. This means Last TieBreak Rank will be selected by default for new projects
3. Possibly update new verbiage on Last TieBreak Rank screen. It currently says: 'When treatment intensity is used to break ties, the tie goes to the treatment with the lowest rx_intensity value'. @jsfried to review and submit changes. We do at least need to change treatment intensity to Last TieBreak Rank

**Comment by jsfried** [comment]
There is a shortage of documentation, explanation and instruction in core analysis, and on these screens associated with the tiebreaker tab in particular. There are actually 3 screens associated with tie breaking. The main tie break screen showing the two rows under "Step 1" (1), the FVS variable selection screen if FVS Variable is selected and the user presses Edit (2), and the Treatment Intensity edit dialog (3). 

Please see attached for changes.
[TieBreakInterfaceChanges.docx](https://github.com/USFS-PNW/Fia-Biosum-Manager/files/1753531/TieBreakInterfaceChanges.docx)

Jeremy will write user guide and help text for this reconfigured dialog and supply on Monday.

**Comment by lbross** [comment]
Please see attached with questions/comments on proposed changes. Let me know if you want to discuss.
[Issue_129_TieBreakInterfaceChanges.docx](https://github.com/USFS-PNW/Fia-Biosum-Manager/files/1760105/Issue_129_TieBreakInterfaceChanges.docx)

**Comment by jsfried** [comment]
Please see responses.
[Issue_129_TieBreakInterfaceChanges_jfedit.docx](https://github.com/USFS-PNW/Fia-Biosum-Manager/files/1760336/Issue_129_TieBreakInterfaceChanges_jfedit.docx)

**Comment by lbross** [comment]
I've spent a couple of hours trying to make the checkbox for tie-break rank appear disabled. The ListView control, of which it is a part, works well but provides few options for customization. The closest I've been able to get is to grey-out the text on the rest of the row. Ironically, I can format everything EXCEPT the checkbox itself. Let me know if you think this is close enough or if you have any other suggestions. Don't want to spend much more time on this minor change.
![tie-break rank](https://user-images.githubusercontent.com/11527966/36810119-b5dcc460-1c7e-11e8-90bd-98a1fe9262f7.png)

**Comment by lpotts** [comment]
Lesley,

I believe a list view is being used.  You can use the code below to NOT allow the user to uncheck it.  The code below DOES NOT allow a user to check the box.  The code will need to be slightly modified to NOT allow the user to UNCHECK it.

private void lstAudit_ItemCheck(object sender, ItemCheckEventArgs e)
        {
            if (handleCheck)
            {
                if (cmbAudit.Text.Trim() == "Assess Data Readiness: Check If Each FIA Tree Spc, FVS Variant, And FVS Tree Spc Combination Is In The Tree Spc Table")
                {


                    ListViewItem oItem = lstAudit.Items[e.Index] as ListViewItem;
                    if (oItem != null)
                    {
                        if (e.CurrentValue == CheckState.Unchecked && oItem.SubItems[lstAudit.Columns.Count - 1].Text.Trim() == "Y")
                        {
                            MessageBox.Show("Cannot check this record: Combination of fvs variant and tree species already exists in the tree species table", "BIOSUM");
                            e.NewValue = e.CurrentValue;
                        }
                    }


                }
            }
            else handleCheck = true;

        }

**Comment by lbross** [comment]
Yes. I'm doing something similar to prevent the user from unchecking the box but Jeremy was hoping for a visual queue on the ListView. I'm not popping a MessageBox at this time when they try to click it. Not sure if we want to do this or not?

**Comment by lbross** [comment]
Note that I am renaming Treatment Intensity to Last Tie-Break Rank and FVS Variable to Stand Attribute on the Tie Breaker and Optimization screens only. I am not changing the column names in the scenario_results.mdb output. I know this isn't ideal but want to make sure it's not a showstopper. I can also change the field names in the output, but this is a more significant undertaking since it means changing all of the SQL used to query and generate the output.

**Comment by lpotts** [comment]
To have more control over objects within the listview, one would need to use the ListViewEx.cs class. It is an extended class that allows controls to be embedded within the listview.  I don’t think, at this point, you want to do that for such a small change to a checkbox.

-Larry

**Comment by jsfried** [comment]
This is a big improvement! Jeremy violated his Feb 23 commitment to provide help text, so here it is, belatedly. 
[Chpt 6 Core help screens_20180518.docx](https://github.com/USFS-PNW/Fia-Biosum-Manager/files/2018253/Chpt.6.Core.help.screens_20180518.docx)

We almost but not completely disappeared rx_intensity-- it still appears as the column heading in the Last Tie-Break Rank screen :-(  Can this be changed to show "Last Tie-Break Rank" instead (and the help text edited to reflect this)? Since we dropped rx_intensity everywhere else, a user is likely to be even more confused encountering it here. If it is a huge deal to change the column heading, then we at least need to add instructional text under "Last Tie-Break rank" dialog title that tells users to enter the Last Tie-Break Rank in the column inexplicably named rx_intensity.

What exactly happens in the Audit Tie Breaker Specifications step? I made a guess in the Help Text, but am having a hard time imagining out a user could foul up the specification given the interface control on this. @lbross

**Comment by lbross** [comment]
rx_intensity is the name of the column in the underlying database, so renaming it will require version_control for legacy projects to continue to function. I have notes in my design document to rename this field, along with a couple of other schema changes, to fully exorcise rx_intensity as part of the Core Analysis enhancements. I'm planning to rename the column: tiebreak_rank because Access has some prohibitions against spaces and hyphens in the field name.

The Tie Breaker audit ensures that there is a rank for every prescription and that there are no duplicate ranks. In practice, the grid edits should take care of nulls but I think we should leave this button in place. Identifying any duplicates is particularly important for this function to work as desired. The audit code also runs automatically prior to a Core Analysis run so users don't have to run it here unless they want to.

Closing because original issue is fixed!
