### ISSUE TITLE
Documentation: How is each table created, used, and updated throughout BioSum

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#149]
We need documentation that goes step by step through BioSum explaining how each table is created and when they’re used to create/update other tables downstream. Specific calculations for each column can probably be glossed over, but analysts would probably want to know where values come from. Having leftover work tables with links that don’t work if you share projects with other analysts should probably be cleaned up if there’s no more use for them. This documentation will be done by whoever is working on that BioSum module already over the course of months. @sorgtyler with start with a sample from FVS input/output. After the concept/format is approved, we will add other modules.

**Comment by sorgtyler** [comment]
@lbross @jsfried I have a WIP document for the FVS Input/Output phase, hosted here: [box link](https://usfs.box.com/s/1pqko614f5whje7zn652og565a8dof29). 

Since FVS is a black box, I don't go into how the FVS output tables are created. I wrote an outline of the order of execution of subroutines in the FVS Output Data Append step, but I wasn't sure how much detail was desired since a lot of it is linking to FVSOUT tables, counting groups, comparing IDs, etc.

I also started an appendix of queries to refer to, which I think will help to concisely show which columns come from where between FIADB -> Biosum Master or Master -> FVSIn.

**Please let me know if you have ideas of what would be helpful to clarify for an analyst reader in the bulleted FVS Output Data section. Is there a better way to list the queries, especially as we add more?**

**Comment by jsfried** [comment]
Looks good!

**Comment by lbross** [comment]
Might we want to reopen this and keep it open until we have documented the rest of the modules?
