### ISSUE TITLE
FVS: Send downed woody material (DWM) to FVS

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#160]
Include DWM and surface fuel model in FVS input. We currently send no information. Per Chad Keyser, if we send in a surface fuel model, that will be used first. DWM data is used if no surface fuel model is provided. Send in nulls rather than 0 if we want FVS to fill in the blanks for missing DWM data.

**Comment by sorgtyler** [comment]
### Summary:
FVS_StandInit.Fuel_Model overrides values in the FWD, CWD, and Duff/Litter columns if it is not null unless specified by the `FuelModl` FVS-FFE keyword. Nulls in these fuel columns allow FVS to fill in blanks using defaults for that variant, but 0s are are left as 0s. Soft/Rotten FWDs are set to 0 because FIA does not track species/decay information in FWD sized pieces. Lastly, it is possible to use custom columns in FVS_StandInit to decide whether to reset fuel values.

### Jeremy's questions (bolded) and Chad Keyser's answers (italicized):
1. **How will FFE handle incomplete population of down wood columns in standinit table? Where some values are nulls because they were not sampled and others are populated?**
    - *If the fields are blank, then FVS will dub in values based on the variant’s default method for assigning down wood amounts. This is explained in chapter 4 of the FFE Users Guide. If you put a zero in the field, FVS will interpret that as being 0 tons/acre.*
        - **I understand how the defaults are assigned. My question centers on what happens if some fields are populated- say, all the down wood over 3” but not the categories under 3” (because they were not sampled, and thus have nulls, not zeros). Does FFE assign defaults only to the down wood categories less than 3” or to all down wood categories?**
            - *I should have said that if any fuel field is blank, then FVS dubs in a value for the empty field. So you can fill in all down wood columns but one and FVS will dub in a value for the one field and only that field. So in your example, FVS would only assign values in the size classes under 3” and use the inventory for 3” and above.*

2. **If down wood columns are populated AND surface fuel model is populated, will down wood have any impact on the surface fuel model used in potFire calculations initially, or in future cycles? Or will only the FuelModel field be used?**
    - *If a user populates the surface fuel model field, this fuel model is used in determining potential and simulated fire effects. It remains in use until the user tells FVS to stop using the fuel model, which can be done with the FuelModl keyword.*
        - **So populated down wood columns only affect the FFE choice of surface fuel model when they are populated and fuel model is not?**
            - *Correct, for the most part. By entering a fuel model, you override the logic to assign fuel models. The fuel loads will not be used to assign a fuel model. This remains in place until a user changes the fuel model selection process with a FuelModl keyword. If a user changes the logic of selection to be “automatic selection”, then FVS will choose a fuel model based on one of three options: original logic, new logic, or modelled logic which uses the actual fuel loads to create a new fuel model. This is explained in Appendix B of the FFE Users’ Guide.*

3. **Standinit provides fields for hard and soft fines, but fia does not collect decay class on fine wood. Is it best to put all the fwd biomass in the hard columns?**
    - *Yes, FWD data can all go into Hard/Sound.*

4. **We are generating sample size columns in the fvs_standinit table that contain the transact length sampled, for cwd and fines, and the number of duff and litter pits sampled, so that analysts can have access to these within FVS to make decisions on a stand by stand basis as to whether to use down wood data or instead rely on fvs defaults and calculations or crew estimated surface fuel model. I have heard that extra columns added to these tables are not available in fvs or suppose- is there a workaround for this?**
    - *FVS will not read into the simulation the extra columns automatically, however, there is a way through the Database Extension/Event Monitor that you can bring an unrecognized stand variable into FVS from a database and use it in EM Compute statements and conditional statements. There are some limitations with this, for instance, you can’t use it to alter initial fuel loads, but could use the value in deciding whether or not to reset the fuel models.*

**Comment by jsfried** [comment]
wrt items 2 & 4, I am thinking that FVS does not offer as much flexibility as one might want (deep sigh) such that we would be better off to build the stand.init file that the user wants. This means that BioSum would need to ask for user input on these issues. I can think of 3 reasonable options for users to choose from for item 2 (with the too short decision resolved by limits specified in item 4):
a) Use Observed Fuel Model when available; provide DWM data when not, unless transect too short, in which case provide nulls for fields depending on the short transect (default)
b) Use DWM in all cases except when transect not too short, else revert to nulls (FVS chooses)
c) Use Observed Fuel Model when available, else revert to FVS choosing (puts nulls in all DWM fields)

For item 4, user would need to provide minimum total horizontal transect length (feet) for:
a) CWD
b) Large fines
c) Small and medium fines
I would set defaults for these at 48 feet, 24, 24

**Comment by sorgtyler** [comment]
- *Chad: Another thing you could do is to provide the data but put an “X_” in front of the field name. Then instruct the users to take that off if they want FVS to use the data.*

- **Jeremy: Thanks for the suggestion. Technically, we are prepping a tool that others will use to generate mass FVS input databases, and trying to anticipate some of the confusion and misunderstanding that may arise so as to be a bit proactive. As we are currently planning, the user would select the options and threshold transect lengths in the BioSum interface before the FVSIn.accdb files get made, and their choices would guide what goes into the input fields (data or nulls), and these will vary by stand depending on data availability and the transect length thresholds they choose. Am I correct in thinking that such input can all be processed in a single SUPPOSE simulation, as long as the user is comfortable with the FFE logic (of using surface fuel model when available, and the supplied DWM info when not, and having FVS fill in any and all DWM attributes for stands where they are presented as null)?** 
    - *Chad: The user will be able to do a single Suppose simulation for all stands that use the same variant. Suppose can only run one variant at a time.*

- **Jeremy: What I think I hear you saying is that there is another way to supply info to the FVS user that allows some choice revision after the FVSIn.accdb has been created: via columns that begin with X_ , for example X_Fuel_0_25_H instead of Fuel_0_25_H, etc. If they are supplied as X_ then it is incumbent on the user to rename then in Access to remove the “X_” prepend if they want them to be accessible to FFE. For deactivating fuel model, this seems an easy approach (just rename “Fuel_Model” to “X_Fuel_Model”, right? Which has the same effect as a Fuel_Model column full of null values?). However, for the more fraught task of populating stand level DWM data only for cases where transects are long enough for the analyst to feel comfortable that the local data is superior to defaults, this approach would not work, because the X_ method either nullifies or enables an entire column for all stands. The user would then have to break the dataset into stands for which transect lengths were sufficient and stands for which they were insufficient and run them separately. Do I have this right?** 
    - *Chad: Yes, since you are preparing the database, your method is more appropriate. It’s much cleaner for the user.*

**Comment by lbross** [comment]
Got several SQL errors when loading plots with DWM enabled during testing because FIA source files didn't have the DWM tables. Requested that @sorgtyler add some checks in to ensure the source tables are there before trying to load DWM data and show message to user if they aren't.

**Comment by jsfried** [comment]
Good idea. We are going to have to be pretty vigilant about holding any FIADB database suspect now that they cannot be directly downloaded from fia.fs.fed.us as access databases. Can never assume anything, sadly.

**Comment by lbross** [comment]
Closing per @sloreno
