### ISSUE TITLE
Oracle12c Compatibility

### ISSUE THREAD

**Issue by lpotts** [USFS-PNW/Fia-Biosum-Manager#176]
Forest Service is upgrading its oracle servers to Oracle 12c.  The Oracle 12c upgrade is suppose to happen by the end of DEC 2018. Client computers will then need to have the Oracle 12c client installed. BIOSUM uses the Oracle XE 11g client. These questions  need to be addressed to determine options for the BIOSUM application: 1. Does Oracle have an XE 12c 32bit version?; 2. Can Oracle XE 11g be functional with both Oracle 12c client and Oracle XE 11g installed on the same machine?; 3. Will the application oracle connection strings  continue to be functional?; Will DEVART license need to be upgraded?; Will Visual Studio 2010 support tools for Oracle 12c?

**Comment by lbross** [comment]
Closing. See issue #229. Two different versions of Oracle client did NOT work well together when using BioSum. We switched BioSum to use the Microsoft Oracle Client. We have not used DEVART for a year. Our intent is to remove the Oracle dependency altogether, rather than to upgrade the FCS schema to Oracle 12c.
