### ISSUE TITLE
Accommodate new tables from OpCost

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#18]
OpCost v6.3.2 outputs two new tables: OpCost_Chipping and OpCost_Ideal. Sara reports that she cannot locate these tables after OpCost has run through the PROCESSOR. BioSum runs a clean-up script after completing PROCESSOR tasks that is deleting these 2 new tables. Quick fix is to add the two tables to the list of tables that is NOT deleted. Recommend additional discussion for where the data in these tables should live long term.

**Comment by lbross** [comment]
Posted [installer for v5.5.7](https://github.com/USFS-PNW/Fia-Biosum-Manager/releases/tag/5.5.7) in GitHub releases. I consider this a temporary fix as the information is not consolidated in a single table. Example database name holding new tables: OPCOST/input/OPCOST_Input_P001_100_100_100_100_2016-04-01_02_17_45_PM.accdb.

**Comment by jsfried** [comment]
Yay! I take it this means that Sara can now test this OpCost version when she has time


Jeremy Fried
Research Forester

Forest Service
Pacific Northwest Research Station, Forest Inventory and Analysis

p: 503-808-2058<tel:503-808-2058>
c: 503-702-9564<tel:503-702-9564>
jsfried@fs.fed.us<mailto:jsfried@fs.fed.us>

620 SW Main St., Ste. 400<x-apple-data-detectors://1/3>
Portland, OR 97205<x-apple-data-detectors://1/3>
pwnfia.info<http://pnwfia.info/>

Caring for the land and serving people



On Apr 1, 2016, at 4:02 PM, Lesley <notifications@github.com<mailto:notifications@github.com>> wrote:


Posted installer for v5.5.7<https://github.com/USFS-PNW/Fia-Biosum-Manager/releases/tag/5.5.7> in GitHub releases. I consider this a temporary fix as the information is not consolidated in a single table. Example database name holding new tables: OPCOST/input/OPCOST_Input_P001_100_100_100_100_2016-04-01_02_17_45_PM.accdb.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/USFS-PNW/Fia-Biosum-Manager/issues/18#issuecomment-204601975>




This electronic message contains information generated by the USDA solely for the intended recipients. Any unauthorized interception of this message or the use or disclosure of the information it contains may violate the law and subject the violator to civil or criminal penalties. If you believe you have received this message in error, please notify the sender and delete the email immediately.

**Comment by lbross** [comment]
Yes she can.

**Comment by sloreno** [comment]
Success.  Both the OpCost_ideal and OpCost_Chipping showed up in my
OPCOST_Input database.  Thanks Lesley!

I noticed when I downloaded this version, the software name in the Start
menu as well as the automatically created shortcut for BioSum, said "FIA
Biosum manager 5.5.5". It should be 5.5.7 I believe.

**Comment by lbross** [comment]
Thought I caught that :-( I posted a new [installer for v5.5.7](https://github.com/USFS-PNW/Fia-Biosum-Manager/releases/tag/5.5.7) that updates the shortcut version number. This is the only difference from the earlier version so it's not time-sensitive to test it. You'll want to uninstall the previous version before installing this one.

**Comment by lbross** [comment]
Saving off notes for future work on these OpCost tables
=============================================================================

On Fri, Apr 1, 2016 at 2:54 PM, Fried, Jeremy - FS <jsfried@fs.fed.us> wrote:
I guess I don't know how all the OpCost outputs from all the packages and variants are currently gathered up into one table-- don't know if that happens at the same time the individual package OpCost databases get made and populated from data in the temp directory space or if biosum goes back to all those access databases and concatenation it into one table later. Ideally this extra info would feed into a harvest costs supplemental database that lives in the same  scenario directory where harvest costs lives, and would only get populated when those supplemental tables are getting spit out (which happens when the analyst sets a flag in OpCost)

=============================================================================
From: Lesley Bross [mailto:lbross@pdx.edu] 
Sent: Monday, April 04, 2016 3:42 PM
To: Fried, Jeremy - FS <jsfried@fs.fed.us>
Cc: Bell, Conor (conorb@uidaho.edu) <conorb@uidaho.edu>; loreno@pdx.edu; Potts, Larry D -FS <lpotts@fs.fed.us>
Subject: Re: Biosum Arguments

 
It appears that BioSum consolidates outputs from all of the packages and variants immediately after OpCost runs. There is a record in the harvest_costs table for each condition + rxpackage + rx + rxcycle. Things are further broken out by species in the tree_vol tables.
 
It sounds like we want something similar to happen with these two new tables. Is the table structure for the new OpCost tables finalized to the point where we can develop a spec for a new supplementary output database/table? Is the data of the same grain so that the two new tables could be combined as one? I notice that OpCost_Ideal has an rx_year column whereas OpCost_Chipping does not.
 
Thanks -- Lesley

Lesley,
 
=============================================================================
The new OpCost tables are not in any way final or ready to splice into BioSum process. They are provided so that we can explore some issues (e.g., with respect to how to handle chipping cost estimation and the material that we specify as getting chipped that is actually of large size) and opportunities and with the idea that in the long term, we may want OpCost to select the harvest system that is cheapest, rather than the one the analyst specified (or at least provide an option for it to do so). However, I don’t even yet understand what is in the Ideal table or how OpCost decides which systems are potentially suitable, nor am I certain that the OpCost selected systems are compatible with the same handling of residues (e.g., utilization by yarding to the landing, versus leaving or treating in the woods) which has implications for processor. This is a back burner issue for now.
 
Jeremy

**Comment by lbross** [comment]
Closing issue. v5.5.7 gives the analyst the capability needed to evaluate the new OpCost tables. Will open another issue when tables are ready to be further integrated into BioSum. 

Sara ... if you find the version number is still incorrect on the desktop shortcut, please reopen this issue.

**Comment by lbross** [comment]
From @jsfried: 
Ideally, (long term) I would like to see these outputs tacked on to the OpCost_output table, provided it is acceptable to write nulls in these fields when the user has not thrown the switch in the OpCost R code to generate this additional information (which would, I expect, make for longer execution time). Long term, it would also be nice to let the user select the option within the BioSum interface, but I think that is still quite a ways off.

Consider renaming OPCOST_INPUT... as it contains both inputs and outputs.

**Comment by lbross** [comment]
Closing. Duplicate. This issue is covered under issue #67: Add columns to harvest_costs table
