### ISSUE TITLE
DATABASE: Replace the FCS process that provides biomass and volume values

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#223]
for regions other than PNW.

From @lpotts:
A couple thoughts.  FCS is a local oracle schema that was specifically used by Kurt to cover western tree species. Another problem is DRYBIOT and DRYBIOM values are obtained differently for each region.  Hence, the BIOMASS tree data moved from the TREE table to the TREE_REGIONAL_BIOMASS table. That is probably why states, other than OR,WA,CA, will have FCS issues with DRYBIOM and DRYBIOT. 

As far as fixing the problem, these things will need to occur:
1.  Ensuring the local FCS schema replicates the DTEAMs processes. We will need a collaborative effort with people like Mark Hatfield and/or Jeff Turner to discuss options.

2. Have a streamlined process for updating the FCS_BIOSUM schema.

Kurt, typically, did a dump of his FCS schema and I had to add additional items like the BIOSUM_VOLUME table and BIOSUM package for volume and biomass calculations.

 I see a problem with the dump process, however. Kurt had oracle database administrative privileges which allowed him to do a dump of his local FCS schema.  As far as I know, nobody in FIA has the oracle database administrative privileges to perform a dump so some other routine will have to happen for FCS updates.

**Comment by lbross** [comment]
The Oracle FCS process requires that an analyst install Oracle XE with administrator privileges. With recent security changes at USFS, this is no longer allowed and prevents BioSum from being installed on USFS computers. We have engaged Jason of the D Team to replace Oracle XE with a Java program that contains the biomass and volume equations. Ultimately Jason's solution should support all variant/species combinations and free BioSum from the Oracle dependency while expanding the number of regions that we can support.

**Comment by jsfried** [comment]
Couple of semi-minor corrections-- 
1) FIA volume and biomass equations are not tied to FVS variant or LOCCODE (those are FVS concepts). They are tied to COND.VOL_LOC_GRP so the expectation is that there will be support for each species present in each VOL_LOC_GRP (kind of a geographic area). Support is needed to calculate, for all trees >1" DBH, the selected FIA cubic foot volumes and biomass values (DRYBIOM and DRYBIOT). We have traditionally used DRYBIOM and DRYBIOT from the tree_regional_biomass table-- I am open to using the equivalant attributes from the Tree table (that are calculated differently) if there is reason to do so. 
2) This, when nationally scoped, is part of what is needed to support BioSum beyond the west coast lower 48 states. The other part is calculating FVS compatible site index and habitat type codes (Plant association codes). One option to consider short of tossing our entire FIADB input module and reweaving BioSum with FIA2FVS (which does not seem to quite exist yet) would be to mine the latter for the info we need and are missing-- FVS compatible site class and plant association code-- these should be available in the STANDINIT FVS table they distribute.

**Comment by jsfried** [comment]
The calculations of volume and biomass for loading from FIADB and from FVS output are validated-- fields are populating correctly it appears and compare favorably to calculations in NIMS. The one remaining issue is the calculations in the troubleshooter tool for the user entered inputs (or user selected row from a loaded table such as a cut list or tree table or sample tree table). Diameter is hard coded when it should not be. Tyler discovered that in addition to this, some of the source for the calculation references selected table row values and other parts source the user entered data. This needs to be resolved. I suspect it would make more sense to have the option of COPYING inputs from the row to the text boxes on the lower part of the form (though obviously not all inputs get copied there) and then there is no ambiguity of what the calculate volume and biomass button does—it operates on the text boxes displayed there (which the user can edit) whether that is the default tree record, something the user has entered or something copied from the matrix above. For inputs that are not shown in these textboxes, it goes with hard coded defaults or with whatever was on the row (if the row was copied there). It would, however, be better (in an ideal world) if all input fields had a text box so that they can be seen, even if many of them will not be modified (or have any effect for PNW users).

**Comment by lbross** [comment]
Closing. We will handle the Troubleshooter updates in a separate issue #268 after the FICS jar implementation issue #262.
