### ISSUE TITLE
FVS: Unable to append output when processing grow-only package

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#224]
for all 4 cycles and did not have cutlist trees.
From @lpotts

**Comment by jsfried** [comment]
This has been identified as an issue a year or more ago, I think, but apparently never definitively addressed. We DO need to be able to load grow-only packages into the PREPOST tables, so that they can be picked as best in optimizer and so that they can be the basis of weighted variables (e.g., subtracted from a package's accomplishment to represent the difference made by the package). I feel like we are able to do this in some projects (I know I have done analysis in BM11 where I used pkg 999 in such differencing so it must have gone into the PREPOST tables somehow-- why wouldn't this always happen?). They don't need to go through processor, unless they are not truly grow-only (e.g., if they incurred surface fuel treatment costs, I think that might need to go through processor, but I am not entirely sure).

@lpotts, @sloreno, @lbross

**Comment by lbross** [comment]
This issue pertains to an emergency fix @lpotts submitted for @sloreno. BioSum crashed when she tried to append FVS output for grow-only prescriptions (without cut lists) and there was no way to get around it. We have issue #208 open for the larger question of including these grow-only prescriptions in Optimizer analysis. Populating the valid_combos table currently requires entries in the tree vol val table so these grow-only prescriptions would be dropped if they didn't go through processor. We hope that @sloreno finds a way to include them in the Optimizer tables, as she has previously, and that we may be able to automate this process once we determine what it is.

**Comment by lbross** [comment]
From @sloreno:  Larry, your fix worked like a charm, no issues appending the package this time around. Closing!

**Comment by lbross** [comment]
Sample KCP file with comments from @sebbusby:
```
!! The IF statement sets up the trigger for the treatment component. The number parameter after IF         
!! refers to the minimum number of years before the statement is revaluated. The statement will be         
!! evaluated every cycle.

IF                 0     !! The treatment component trigger, fully customizable. In this case, the trigger is Cycle = 1
CYCLE EQ 1
THEN 
!! This is where the user would insert keywords associated with a treatment component that incurs costs 
!! and doesn't explicitly involve cutting trees, such as a fuel treatment like broadcast burn or pile burn.

COMPUTE            0          
ACTIVITY = 1
END
ENDIF

!! A value of 1 is written in the FVS_COMPUTE table for each stand and cycle where the treatment             
!! component was triggered.
```
