### ISSUE TITLE
PROCESSOR: Fails with Cannot find table or constraint error

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#267]
Also errors when building additional harvest costs worktable. Occurs with one or multiple packages. @lbross tracked it down to creating a new ado_data_access object in the Processor object rather than using the one passed in from the user control. This didn't cause errors in the BlueDemo project, but does not reliably work for all projects. Switching back to previous configuration.

**Comment by jsfried** [comment]
Getting away from ado really is a necessity, I now see.

Sent via iPhone. Forgive the brevity, typos and lack of nuance.
________________________________
From: Lesley ***@***.***>
Sent: Tuesday, November 30, 2021 2:03:23 PM
To: USFS-PNW/Fia-Biosum-Manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [USFS-PNW/Fia-Biosum-Manager] PROCESSOR: Fails with Cannot find table or constraint error (Issue #267)


Also errors when building additional harvest costs worktable. Occurs with one or multiple packages. @lbross<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flbross&data=04%7C01%7C%7C83179b5cc3184305eb8108d9b44d3a6c%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637739066052936595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HfXw3zWhb91Cxz8BxcZ8fjp7iEwwIz9VmnI6yv%2BXNVU%3D&reserved=0> tracked it down to creating a new ado_data_access object in the Processor object rather than using the one passed in from the user control. This didn't cause errors in the BlueDemo project, but does not reliably work for all projects. Switching back to previous configuration.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSFS-PNW%2FFia-Biosum-Manager%2Fissues%2F267&data=04%7C01%7C%7C83179b5cc3184305eb8108d9b44d3a6c%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637739066052946553%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ARvwC30V12%2B0EsWxvsMCWEDQ6aJvgaP2S%2BAzbFBxcKI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEFM5IG6HCC4ESQRYCV5GEDUOVC2XANCNFSM5JC5HA2A&data=04%7C01%7C%7C83179b5cc3184305eb8108d9b44d3a6c%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637739066052946553%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tvXQheHau2hQDxAHEsvCH1uPEZVNmHV5BZTaPOdgD1w%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C83179b5cc3184305eb8108d9b44d3a6c%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637739066052956501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=d4OcPnGQNS5fnE5SD%2FIjZSzARAo1hvwobb1N4Y3wRZM%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C83179b5cc3184305eb8108d9b44d3a6c%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637739066052956501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RTZfev1Uc7vIBdNTfOEXUXXEudI93o97o5uPsiU7HZE%3D&reserved=0>.




This electronic message contains information generated by the USDA solely for the intended recipients. Any unauthorized interception of this message or the use or disclosure of the information it contains may violate the law and subject the violator to civil or criminal penalties. If you believe you have received this message in error, please notify the sender and delete the email immediately.

**Comment by jsfried** [comment]
Tested processor on the hefty CEC project. Was able to move around in the processor input screens with no errors. Was able to open additional harvest cost edit screens with no problems. Made a copy of the processor scenario, ran a package in it, no problems. Delightful outcome!
