### ISSUE TITLE
PROCESSOR: Add option to trigger additional CPA from FVS_COMPUTE flags

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#295]
The current implementation charges the additional CPA when harvest occurs regardless of whether the additional CPA was actually incurred. It supports manually assigning the additional CPA to a database table but this is often untenable due to large volumes. This enhancement will allow FVS to indicate if an additional cost was incurred for a given plot/rx/rxcycle. The inactive stands processing will be modified to be controlled by the same FVS_COMPUTE flags.

**Comment by sebbusby** [comment]
Validated using the Douglas Cty project, Processor is correctly using flags in the FVS_COMPUTE table to assign additional harvest costs. Awesome addition!

**Comment by jsfried** [comment]
Can the tab in processor be relabled Additional CPA (instead of Supplemental Harvest Costs, a label we’ve retired)?

**Comment by jsfried** [comment]
Name (of cost component) leading with a numeral is not allowed by error message does not explain that. Leading with an underscore- a supposedly allowable character, yields this error:
![image](https://user-images.githubusercontent.com/17485472/229412313-80adc2a4-d2dc-4ed8-b037-8b575e8e30ff.png)

**Comment by jsfried** [comment]
@lbross OK, yes that is confusing. I entered the name in the dialog presented in the Processor Supplemental Harvest Costs tab when you click on the button to add a scenario level CPA. In this dialog it IS restricted to 8 letters and no special chars etc and can't start with a digit but the guidance displayed in the error dialog is not complete and a leading underscore presents an !!Error!! I guess it really does not need to be restricted to FVS compatibility rules because a scenario level cost can be labeled any which way that Access (and soon SQLite) will accept, right?

**Comment by lbross** [comment]
A scenario-level cost can have any label that Access/SQLite support. Unfortunately the error message you shared with the "_" leading the column name is generated by the database and there is no way for me to intercept it. I can only be proactive on the front-end and disallow a leading "_". I will add this to the list of input edits for this field.

**Comment by jsfried** [comment]
And maybe we update the docs to say lead with a letter!

**Comment by lbross** [comment]
No argument from me on the docs. I assume neither of these is critical enough to generate a new .msi that is different from the one you are already using? They'll be sitting there waiting for v5.10.2.
