### ISSUE TITLE
DATABASE and FVS: Enable DWM settings by default

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#307]
1. Enable 'Use Down Woody Materials Data' on plot load screen by default
2. Enable 'Calculate fuel biomasses with DWM data ... ' on FVSIn Options by default
3. Set all 3 minimum transect lengths to 1 on FVSIn Options by default

**Comment by lbross** [comment]
Another change. From @jsfried: I think we don’t want the Scott and Burgan fuel models checked by default because if they are in the FVSIN file, they will be used instead of the down wood data—and Sebastian found that actual fire effects were better predicted using FIA down wood fuels info than by the FIA surface fuel model crew call.

**Comment by sebbusby** [comment]
Validated, looks good

**Comment by jsfried** [comment]
In FVS module, user can choose to include seedlings and to include DWM data in one of two ways (as fuel model or as DWM to guide FFE in setting fuel models). In DATABASE module, user should choose to LOAD these data into BioSum, not to "include" them else it is confusing (check boxes to include in two different modules). Proposing a change to the language on the screen:

instead of this:

![image](https://github.com/USFS-PNW/Fia-Biosum-Manager/assets/17485472/800f984c-792d-4fb1-bdcd-60e022172b63)
 we would have:

ckbox   Load seedling data to BioSum
ckbox   Load down wood material data to BioSum

**Comment by jsfried** [comment]
And in the FVS In options screen, these changes would improve accuracy, consistency and clarity:
1. Under "Include Scott and Burgan..." a line of text stating: "If surface fuel models included. FVS will ignore all DWM data loaded"
2. "**Include c**alculated ..."
3. Minimum Small **and Medium** FWD Transect Length (ft)
4. "**Tree Growth** Calibration Data"
5. "**Include** previous height**, where available**"
6. "**Include** previous diameter**, where available**"

**Comment by lbross** [comment]
@jsfried: Please review cosmetic changes requested for UI's. This will be in the next release. v5.10.1 or v5.11.0.
![image](https://github.com/USFS-PNW/Fia-Biosum-Manager/assets/11527966/4a148ac8-23e6-4681-802d-df395b457002)
![image](https://github.com/USFS-PNW/Fia-Biosum-Manager/assets/11527966/ae320aa1-85a0-4ab9-8fce-5e87f6496399)

**Comment by jsfried** [comment]
Confirmed by Evan Patrick on 6/14/24
