### ISSUE TITLE
OPTIMIZER: Remove references to FVS PRE-POST Context Database

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#311]
The new SQLite FVS Out processing puts all of the PRE-POST tables in a single SQLite database negating the need for the FVS PRE-POST Context Database. FVS PRE-POST weighted tables are in their own database for all variant/packages: optimizer/prepost_fvs_weighted.db. These two database can be attached if they need to be queried together.

1. Remove 'Populate FVS PRE-POST Context Database' line item from the Run Scenario screen and update progress indicator to account for this missing step
2. Remove any code behind this line item that isn't shared with other processes
3. Remove fvs_context.accdb checkbox from the 'Export to SQLite' form.
4. Remove any code behind that line item that isn't shared with other processes

**Comment by druepdx** [comment]
I just pushed an update to my fork with references to the FVS Context database removed

**Comment by jsfried** [comment]
On the Wallowa Start project., I upgraded the project to 5.11 and opened the Run simulation tab. The context database checkbox is still there. Thinking that I might need to make a new optimizer scenario, I created a new scenario in the project and attempted to copy the existing scenario into it. This process crashed every time, with an exception error and the following detail:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at FIA_Biosum_Manager.uc_optimizer_scenario_psite.loadvalues_FromProperties()
   at FIA_Biosum_Manager.frmOptimizerScenario.CopyScenario()
   at FIA_Biosum_Manager.frmOptimizerScenario.tlbScenario_ButtonClick(Object sender, ToolBarButtonClickEventArgs e)
   at System.Windows.Forms.ToolBar.OnButtonClick(ToolBarButtonClickEventArgs e)
   at System.Windows.Forms.ToolBar.WmReflectCommand(Message& m)
   at System.Windows.Forms.ToolBar.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4724.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
FIA_Biosum_Manager
    Assembly Version: 1.0.8910.23564
    Win32 Version: 1.0.8910.23564
    CodeBase: file:///C:/Program%20Files/FIA%20PNW%20Portland%20Forestry%20Sciences%20Lab/FIA%20Biosum%205.11.0/FIA_Biosum_Manager.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4654.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4718.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4724.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4724.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4724.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4690.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Microsoft.Office.Interop.Access.Dao
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4420.1017
    CodeBase: file:///C:/windows/assembly/GAC_MSIL/Microsoft.Office.Interop.Access.Dao/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Access.Dao.dll
----------------------------------------
SDP
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/FIA%20PNW%20Portland%20Forestry%20Sciences%20Lab/FIA%20Biosum%205.11.0/SDP.DLL
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.118.0
    Win32 Version: 1.0.118.0
    CodeBase: file:///C:/Program%20Files/FIA%20PNW%20Portland%20Forestry%20Sciences%20Lab/FIA%20Biosum%205.11.0/System.Data.SQLite.DLL
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4724.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4724.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
StandByAnimation
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/FIA%20PNW%20Portland%20Forestry%20Sciences%20Lab/FIA%20Biosum%205.11.0/StandByAnimation.DLL
----------------------------------------
ProgressBarBasic
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/FIA%20PNW%20Portland%20Forestry%20Sciences%20Lab/FIA%20Biosum%205.11.0/ProgressBarBasic.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by druepdx** [comment]
@jsfried is the FVS Context checkbox still there or just the other Context checkbox?

**Comment by jsfried** [comment]
Right you are-- got those confused. FVS Context is gone.

**Comment by lbross** [comment]
Do we have a new (v5.11.0) problem of not being able to copy Optimizer scenarios? From the stacktrace it looks like it's having trouble copying the psites?

**Comment by druepdx** [comment]
I found and fixed the error. I just pushed my changes.
