### ISSUE TITLE
FVS: Failed pre-audit (Step 2) when processing BioSum output data 

### ISSUE THREAD

**Issue by Cat-Ducat-USDA** [USFS-PNW/Fia-Biosum-Manager#361]
I created a new project to use for 5.11.1 validation. When I got to the output data stage and initiated the pre-audit, it returned a failed audit message stating "FVSOut.db ERROR: 761 fvs_cutlist trees for variant PN could not be found in the FIADB tree table by matching FVS_Tree_Id (see audit table audit_fvs_tree_id). Jeremy and I have both verified that the trees are present (all with IDs, no nulls) in master.tree and FVS_Cutlist tables, but the audit_fvs_tree_id table indicates the tree IDs are not found. All 761 trees are not being found.
We also ran an old project through 5.11.1 to see if we could replicate, but the audit passed for the older CWI project.

I posted the zipped project, called cwi_5.11.1validation_10.01.24, in the temp 30 days folder.

**Comment by lbross** [comment]
We might need to go back to the fiadb database to troubleshoot this one. Can you tell me which state you are using? And the file date/size so I am sure we have the same one?

**Comment by Cat-Ducat-USDA** [comment]
Hey Lesley, I am using the Washington FIADB data - I am zipping it up and am posting it in the temp 30 days folder. It says the total size of the folder is 1987 MB. It should be up in the next few mins.

**Comment by Cat-Ducat-USDA** [comment]
Sorry, 247,886 KB total size of the 7z file.

**Comment by lbross** [comment]
Just found that this is a problem with the SQL statement for the audit and that the data in your test project is fine. I need to add some trim() statements in the SQL where we are joining on fvs_tree_id. We've run into this before when joining MS Access tables to SQLite tables, but I am puzzled that it worked in v5.11.0 but doesn't in v5.11.1. Maybe the data format is slightly different in the source FIADB database? Anyhow ... it's an easy fix that we should get into v5.11.1. I'll post a new .msi soon.

**Comment by Cat-Ducat-USDA** [comment]
Oh excellent! Do you still need my plot data, or is this good to go?

**Comment by lbross** [comment]
I've got all I need for now. Thank you!!

**Comment by Cat-Ducat-USDA** [comment]
Hey Lesley, so... bad news bears. I am working on the new 'starter project' using plots in CWI. When I ran the pre-append audit (FVS Output data), I got this error message again saying that cutlist trees for variant EC could not be found in the FIADB tree table by matching FVS_Tree_Id. Did we ever find a solution for this issue? The issue could be with the plot data, maybe? This is not the exact same plot data we used for the actual CWI project.

**Comment by jsfried** [comment]
I suspect that we might find a workaround by trimming extra spaces out of whichever column has them. Can look at this with you after 3 or 3:15 most likely

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cat-Ducat-USDA** [comment]
Sounds good Jeremy, thanks!

**Comment by lbross** [comment]
This is fixed with the next version that nobody has yet. 98% that it's a red herring. I would continue with the remaining steps of the project.

**Comment by Cat-Ducat-USDA** [comment]
That would make sense, the tree cut recs column still populated and there are trees in all of the relevant tables. Fabulous, thanks!

**Comment by Cat-Ducat-USDA** [comment]
Well... ended up getting this. If it's a plot data issue, Jeremy and I can look at it this afternoon, but I have never seen this before.
![appendfvsoutdataerror 10 11 24](https://github.com/user-attachments/assets/7895407c-2198-446c-9f12-1cf275aff204)

**Comment by Cat-Ducat-USDA** [comment]
@lbross Jeremy and I took another look through the data and nothing appears amiss. We tried to rerun and reappend but ran into the same error messages. We did note, however, that biomass information is not populating in the FVSOUT_TREE_LIST in the FVS_CutTree table, specifically... seems like there's a Java code-related issue. I zipped up the folder (titled cwi_mini_24.10.11) and put it in the temp 30 days box!

**Comment by lbross** [comment]
This is usually an issue with the java setup on the host computer. Do you still have v5.11.0 on this computer? If so, could you try an FVS append with an older project? If it's a problem with the java configuration, it should fail everywhere. You may also want to double check to see if you have a JDK >= 1.8 installed. If this is a USFS computer, it's possible that I/T pushed a software update that broke java. I believe the USFS options for this component are Oracle SDK and OpenJDK

**Comment by lbross** [comment]
Just ran into a related issue in Processor where fvs_tree_id needs to be trimmed before it can run successfully. I'll try to post a new .msi for Cat soon so that she can successfully create the reference project. This doesn't have anything to do with the Java error though, so that can be worked through if I don't get the .msi out right away. But don't try to run Processor for now.

**Comment by Cat-Ducat-USDA** [comment]
I do not still have v5.11.0, but can redownload if needed? IT definitely pushed some kind of software update... but I found OpenJDK and am downloading it presently. After that I'll download the new msi!

**Comment by Cat-Ducat-USDA** [comment]
I installed OpenJDK and it still did not fix the Java execution error. Looking like I'll need to get on with help desk. I have downloaded the new msi but need to fix this part first I suppose.

**Comment by lbross** [comment]
Hi Cat. Did you restart after installing OpenJDK? This tripped me up a couple of installs ago. If you type 'java -version' at a command or powershell prompt it should tell you which version of Java is installed. I also had to restart after installing the SQLite ODBC drivers on a new Windows 11 computer which I haven't had to do before ...

**Comment by Cat-Ducat-USDA** [comment]
> Hi Cat. Did you restart after installing OpenJDK? This tripped me up a couple of installs ago. If you type 'java -version' at a command or powershell prompt it should tell you which version of Java is installed. I also had to restart after installing the SQLite ODBC drivers on a new Windows 11 computer which I haven't had to do before ...

Yes, I did! Was forced to.

**Comment by lbross** [comment]
Can you tell me what it says when you run the java -version command? I'll download and take a look at cwi_mini this morning.

**Comment by Cat-Ducat-USDA** [comment]
It says 'java-version' is not recognized as an internal or external command, operable program or batch file.'

**Comment by Cat-Ducat-USDA** [comment]
Yep, I realized that after I commented... just edited my earlier comment to reflect what it actually says.

**Comment by Cat-Ducat-USDA** [comment]
Full message: 
openjdk version "11.0.24" 2024-07-16 LTS
OpenJDK Runtime Environment Microsoft-9905872 (build 11.0.24+8-LTS)
OpenJDK 64-Bit Server VM Microsoft-9905872 (build 11.0.24+8-LTS, mixed mode, sharing)

**Comment by jsfried** [comment]
This is what mine shows: 

C:\Windows\SysWOW64>java -version
java version "1.8.0_421"
Java(TM) SE Runtime Environment (build 1.8.0_421-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.421-b09, mixed mode)

Lesley- Can you run the mini project on your computer?

**Comment by lbross** [comment]
I'm getting the error again for the audit and it's throwing a java stacktrace with it tries to run the FICS .jar. This is something we haven't seen before. I'm digging into it. No further action required from your side at this point.

**Comment by jsfried** [comment]
Ugh! this suggests there is something different in the kind of input we are throwing at FICS in cwi_mini vs other projects, right? You can't complain that BioSum lacks code diversity! My hats off to those of you capable of handling debugging in C#, R, Java, Microsoft frameworks (Db engine, DAO, ADO), SQLite, etc. with such aplomb. Good luck with it!

**Comment by lbross** [comment]
Right. The error suggests something to do with the spcd. I'm about to send it to Jason. I found some spcd = -1 in the biosum_calc table which is bizarre because there aren't any in master.tree like this. But even when I deleted them, it wouldn't work. It may be another place where fvs_tree_id isn't joining correctly. I'll keep you posted.

**Comment by jsfried** [comment]
Could our jar not be set up for 4 digit species codes?

**Comment by jsfried** [comment]
I see lots of -1 values in species in the biosum_volumes_input table of FVSOUT_TREE_LIST.DB. I checked the biosumCondId of one of them and that cond does not even show up in master.cond of the project-- not sure what is going on there...

**Comment by jsfried** [comment]
So for clarity, since we've tasked Cat with getting a demo project put together as a top priority, she needs to switch to something else whilst you and Drue resolve these issues, right?

**Comment by lbross** [comment]
This one's on me currently, but yes. I think I just found some trees in master.tree that don't have parent records in master.cond. I'm not sure how that could possibly happen so I may need some help with that once I confirm.

**Comment by lbross** [comment]
@Cat-Ducat-USDA  Can you send me the list of plot_cn's that you used to create this project? I have found 158 tree records with biosum_cond_id not in the cond table. I don't know how this could happen. You can run this query in master.mdb to get the list. I am open to suggestions as to how this might have happened. 
SELECT tree.biosum_cond_id, fvs_tree_id
FROM tree
WHERE NOT EXISTS (SELECT 1 
                  FROM cond 
                  WHERE cond.biosum_cond_id = tree.biosum_cond_id);

**Comment by jsfried** [comment]
[CWI_CNs_2002_2021.txt](https://github.com/user-attachments/files/17384295/CWI_CNs_2002_2021.txt)

We did that strept together and this is the list of CNs that we uploaded, using the latest EVALID (532101) to filter it to those that are in that EVALID (These CNs span from 2002 to 2021).

**Comment by jsfried** [comment]
I just ran that query on the copy of the project on my computer (before I posted it for Cat) and it returned no trees. Cat's current version returns 158 trees. I think that Cat then did the Assign FVS Variant step and I coached her through that because there was something that the BUG docs didn't make clear. She can tell you what she did with the project after that

**Comment by jsfried** [comment]
My copy of the project has 1745 conditions; hers has 1740. I do remember something about trying to remove the conditions that were reserved from the project and that being a struggle that Cat ultimately decided to resolve by exclusing them at the optimizer step. But perhaps conditions got removed and trees did not...

**Comment by lbross** [comment]
OK. Since we haven't see this before, my suggestion is to rewind and continue from Jeremy's version of the project. I think the -1's are coming from these trees that are linked to conditions missing from master.cond. I'm continuing to follow-up with Jason because even when I remove the -1's, I'm still getting the same error.

**Comment by jsfried** [comment]
Agreed. Will let you know whether new project loads FVSOut successfully when we get there. Curious how trees got preserved even with conditions deleted and that their spcd got set to -1. Cat found some other anomaly that she will share with you

**Comment by Cat-Ducat-USDA** [comment]
I created a new project that I am loading the same plot data into currently to see where things were corrupted. I appended the plot data from the correct evalid and the return message said I had 1745 conditions and only 32,920 trees... in master.mdb, it says 40,368 trees. Not sure what that discrepancy is about, but my numbers match Jeremy's at this point. Are we able to do a query to remove trees associated with reserved conditions, then remove the reserved conditions, or will we need to also do this for seedling and sitetree? Ultimately just curious if that would fix the issue... however, we are leaning toward using the new project I am making so that our demo project is 'clean.'

**Comment by jsfried** [comment]
We are going to leave these reserved areas in the project and not attempt to remove them from the master before proceeding on the logic that we want a stable demo that is not potentially corrupted by analyst overrides. We will need to remember to filter them out at the optimizer stage so that we don't accidentally present results that are based in part on logging in wilderness. The intermediate results (volvalbysppdiamclass and harvest_costs) will nonetheless be corrupted as they will contain results for such harvests that cannot actually happen. We can't simply omit plot CNs from the plot load list because reserve status is defined at the condition level not the plot level and a plot can have both reserved and unreserved conditions (even if rare). At some point, we will need to document at safe way for analysts to remove unwanted conditions and their trees (and sitetrees and seedlings to if necessary).

**Comment by lbross** [comment]
Leaving the reserved areas in the project for this demo is the best plan. I don't feel comfortable suggesting a series of queries that could remove these conditions. Maybe once we get the condition zapper rewritten for SQLite, that could be a potential solution. And I don't know that I'd say the Processor output is "corrupted" but yes, it will contain results tat shouldn't be included.
The -1's are showing up in the biosum_calc table (input for FICS) because the query that populates them includes a link to the condition table which prevents those trees from being updated. The spcd in master.tree are fine.

**Comment by Cat-Ducat-USDA** [comment]
Morning all, just wanted to update everyone that I have finally got the new version of cwi_mini (I'm calling cwi_demo) past the FVSOut stage. No cutlist error messages, no java execution issues (which confirms that removing the conditions prior to running but not the trees caused the crash), and no other issues. Successfully passed both audits! On to processor...

**Comment by lbross** [comment]
From @Cat-Ducat-USDA: Audits successfully passed with no errors (cwi_demo)
