### ISSUE TITLE
DATABASE: Obsolete FCS schema results in incorrect DRYBIOT values during tree import

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#91]
From @jsfried:

spcd | COMMON_NAME | CountOfcn | AvgOfDiff% | AvgOfcull
-- | -- | -- | -- | --
21 | Shasta red fir | 20 | 16% | 0.0
64 | western juniper | 314 | 16% | 5.0
81 | incense-cedar | 26 | 22% | 0.0
101 | whitebark pine | 17 | 10% | 0.9
117 | sugar pine | 11 | 15% | 3.0
231 | Pacific yew | 14 | 9% | 10.0
321 | Rocky Mountain maple | 14 | 21% | 0.0
375 | paper birch | 4 | 27% | 0.0
431 | giant/golden chinkapin | 1 | 14% | 0.0
475 | curlleaf mountain-mahogany | 157 | 20% | 1.5
815 | Oregon white oak | 56 | 6% | 0.0

Not sure what is going on, but it is not like these species are always very different- for 81 Incense Cedar, for example, the estimates are quite close until you get below 6” dbh. I guess the PL-SQL code in BioSum is out of date and until we get a more recent version of the package to drop in, we are going to be out of sync on these. I think Larry was exploring with Kurt how to get an updated package to use with BioSum but I don’t recall where that was left.

**Comment by lbross** [comment]
@lpotts has been able to load the new FCS schema but additional work is needed to determine BioSum impacts. The schema name was changed to FCS_BIOSUM so the ODBC connection and documentation needs to be updated.

**Comment by jsfried** [comment]
Ran a test on Nevada County, CA, comparing the BIOSUM produced DRYBIOT to the FIADB versions of this in Tree_regional_biomass (that I did NOT import into the project). The values are now MUCH closer:

![image](https://user-images.githubusercontent.com/17485472/35887783-3e4c6544-0b4a-11e8-983f-ca79da94ed12.png)

They are now within much less than 1% in nearly all cases. Though I remain mildly perplexed as to the reason for differences, perhaps Larry can suggest some. I did download the FIADB database that I am using for this comparison about a year ago, so perhaps there have been fcs changes since then. I am comfortable with this level of difference.
@lpotts may want to weigh in
