### ISSUE TITLE
FVS: Add audit to identify FVS_TREE_ID corruption

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#94]
@lpotts recommends going through each FVS OUPUT file and deleting table records by STANDID.
 
DELETE EVERYTHING BY STANDID=COND.BIOSUM_COND_ID
 
Or
 
DELETE EVERYTHING BY SUBSTR(STANDID,1,LEN(TRIM(STANDID)) – 1) = PLOT.BIOSUM_PLOT_ID
 
The FVS OUTPUT FILES are located in the projectrootdirectory\fvs\data\FVSOUT_variant_Ppackage-cycle1treatment—cycle2treatment –cycle3treatment –cycle4treatment .ACCDB
 
Also, it may be a good idea to have the application clean up the PREDISPOSE file when deleting plots in order to avoid data corruption since PREDISPOSE also contains FVS_TREE_ID values.
 
Tree records in each projectrootdirectory\fvs\data\BiosumCalc\variant_Ppackage_TREE_CUTLIST.FVS_TREE tree table should be cleaned up as well.

**Comment by lbross** [comment]
This enhancement is recommended as a way to avoid corrupting the FVS_TREE_ID assignments when plots are deleted and FVS is re-run. @jsfried  expressed concern about modifying the intermediate output data. @lpotts suggested backing up the databases before cleaning up the records. This could cause a challenge with disk space. Will verify that we want to pursue this during a scheduled DEV call

**Comment by jsfried** [comment]
It’s basically a matter of philosophy and disclosure. If we are going to take a user’s request to delete plot inputs out of master to mean delete those plots and linked info throughout the project, this needs to be quite explicitly conveyed. In many cases, it will make more sense to a user to freeze or abandon a project and start a new one rather than risk deleting modeled output that the user may find useful at some point and which they do not wish to recreate due to unwanted deletion. However, for this strategy to work, it needs to be easier for users to move data among projects—for example prescriptions and package definitions. And there is some risk that a proliferation of project versions (with much duplicate info) will swamp even the largest hard drives.

**Comment by lbross** [comment]
The proposed solution for this issue has changed. Summarizing the new solution:
We need to add a new audit to this screen to warn users when FVS_TREE_ID gets out of sync between the MASTER.TREE table and the FVS OUTPUT tables. We will add this audit between the current steps 3 and 4 on the FVS: Process FVS Output screen. This audit will check the FVS_TREE_ID field in the FVS tables and make sure they can be tied back to the MASTER.TREE table. This will be a read-only audit. Any mismatches will indicate to the user that they have a data corruption problem.

@lpotts will generate the SQL to be used for this audit. Sql in the BM_P002_TREE_CUTLIST.MDB used to troubleshoot the problem can't re-used because it refers to tables that aren't populated yet when we hope to run the audit.

**Comment by lbross** [comment]
Closing per @jsfried. Since we plan to move to a new tree numbering system, spending time validating this audit is moot.
