### ISSUE TITLE
Audit log buttons malfunction in FVS data load module

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia-Biosum-Manager#99]
After working through the 5 steps of loading FVS output data back to BioSum, I clicked on the button labeled "Open Post Audit Log" and got an unhandled exception error stating "could not find a part of the path w:\bs_projects\BM10\fvs\data\treelists". Clicking on the Open Audit Pre/Post table accomplished nothing (nothing opened, no messages appeared).

**Comment by lbross** [comment]
Here are my findings. Need some background from @lpotts before proceeding.

1. "Open Post Audit Log": This button is looking for a text file in the \fvs\data\treelists folder. This folder doesn't exist in any of my sample projects including Jeremy's BM10 project. Is this a valid path for the post audit log? The button is looking for a .txt file within this folder containing the string 
'?_TREE_CUTLIST.MDB_audit*.txt'. I can't find any files with this name in my projects.

If this is indeed a valid search for a log text file, we should add some checks here for the treelists folder and log file. If either doesn't exist, we should pop a user-friendly warning message.

2. "Open Audit Pre/Post table": For this to work, you need to have a row selected in the table. If no rows are selected, we should add a warning here similar to Processor telling the user that they need to have a row selected. This button is looking for a table in the FVSOUT_BM_P023-204-204-204-204_BIOSUM.ACCDB database called audit_fvs_summary_year_counts_table. I could not find this table in any of my FVSOUT files. Is it possible the table was suppressed with the 'Suppress record counts' option in the BioSum application settings? 

I recommend another warning here telling the user that audit_fvs_summary_year_counts_table could not be found rather than silently doing nothing.

3. "Open Pre Audit Log": This works well except that you need to have a row selected in the table when you click it. Recommend a similar check to item 2 where we warn the user if they don't have at least one row selected when clicking the button.

**Comment by lbross** [comment]
2. "Open Audit Pre/Post table": Added user warning if no rows are selected on the table. If a row was selected, everything works as desired. Not sure what the problem was on my initial examination. Jeremy sent me several copies of the project so perhaps the data was better in the most recent?
3. "Open Pre Audit Log": Add user warning if no rows are selected on the table
1. "Open Post Audit Log": Waiting for background from @lpotts; Can't find a treelists subfolder in the \fvs\data folder

**Comment by lbross** [comment]
From @lpotts:

Fixed the problems with the audit buttons on the FVS OUTPUT dialog. Attempting to open a file in the FVS\DATA\TREELISTS folder was creating an error. The error was a result of failing to update a section of code when BIOSUM implemented calculating the VOLUMES and BIOMASS with the FCS oracle equations. All FVS output variants are currently being processed in the FVS\DATA[VARIANT]\BIOSUMCALC folder when previously it was the TREELISTS folder. The post audit lists any records that have a DRYBIOT value of null.

In addition, the <Open Audit Pre/Post Table> button is to allow the user to view the audit tables in the
FVSOUT_[variant]_P[packageid]-[rx1id]-[rx2id]-[rx3id]-[rx4id]_BIOSUM.ACCDB file. Changed the code to check if any audit tables exist in the accdb file and display a message to the user if no audit tables were found.

These are the audit tables:

audit_fvs_tree_id_cut - list each tree and what rx cycle it was cut and whether it was cut multiple times.
audit_fvs_tree_id - List all the CUTLIST trees by FVS_TREE_ID and set a flag of Y if a matching TREE table record is found and N if the FVS_TREE_ID is not found in the TREE table.
audit_fvs_summary_year_counts_table - list all the FVS_SUMMARY records by year and sequence number and whether the record exists in the other FVS OUTPUT tables (ie FVS_CUTLIST,FVS_POTFIRE,FVS_CARBON, FVS_STRCLASS, FVS_TREELIST etc).
fvs_potfire_prepost_seqnum_matrix - List each stand id in the POTFIRE table by sequence number and year and set flags Y or N identifying the PRECYCLE 1-4 and POSTCYCLE 1-4.
audit_FVS_POTFIRE_prepost_seqnum_counts_table - List each stand id and count the number of records for each PRECYCLE 1-4 and POSTCYCLE 1-4.
fvs_strclass_prepost_seqnum_matrix - See item #4
fvs_cutlist_prepost_seqnum_matrix - See item #4.
fvs_summary_prepost_seqnum_matrix - See item #4.
audit_fvs_summary_prepost_seqnum_counts_table - See item #5.

**Comment by lbross** [comment]
This will be in the next BioSum release.

**Comment by jsfried** [comment]
Did extensive testing on this and related issues using Blue 10 Demo project and the FTCE Mid project. Upon entering FVS OUTPUT module in the Blue 10 Demo project, I clicked on PRE AUDIT LOG button and got this:
![image](https://user-images.githubusercontent.com/17485472/35901119-0e9d55fc-0b8a-11e8-8fdf-87deeab24862.png)
Of course I had not run step 3 yet at that point, so there was not audit log to look at; still, it would be better to trap for this condition than toss up an exception, I think.

However, when I attempted to run step 3, I got this message:
![image](https://user-images.githubusercontent.com/17485472/35901198-492c1fdc-0b8a-11e8-914d-9d5f181679ac.png)

Even exiting BioSum (after the exception) and coming back, I got this error when trying to run step 3 (1 and 2 go fine). However, running the FTCE Mid project, I did not get this error.

**Comment by lbross** [comment]
This is due to an error that occurred when merging some code changes together. Shouldn't take too long to fix. I'm seeing the same problem on the POST AUDIT LOG and will fix that as well.

**Comment by carlinstarrs** [comment]
This can be closed (I don't think I can close them)

**Comment by lbross** [comment]
Thanks! Wasn't 100% sure how the permissions worked. I think you can close your own.
